name: Alfresco SSL Generator CI

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
  push:
    branches:
      - feature/**
      - fix/**
  workflow_call:
  workflow_dispatch:

jobs:
  test_new:
    name: "Test new approach"
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '[skip tests]') &&
      !contains(github.event.head_commit.message, '[force]')
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
      - name: "Run testing script"
        run: bash ./scripts/ci/test.sh

  test_legacy:
    name: "Test legacy approach"
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '[skip tests]') &&
      !contains(github.event.head_commit.message, '[force]')
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
      - name: "Run testing script"
        run: bash ./scripts/ci/test_legacy.sh
